name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Semantic version range syntax or exact version of a Python version
      - name: Specify Python Version
        run: python -V
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
